services:
  app:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: "core.settings.production"
      POSTGRES_URL: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      REDIS_URL: "redis"
      REDIS_PORT: "6379"
      REDIS_DB: "1"
    volumes:
      - static_volume:/app/static_files
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/static
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  pgdata:
  static_volume:
