# Generated by Django 5.1 on 2024-08-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_alter_fieldresponse_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="options",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
