# Generated by Django 5.1 on 2024-08-16 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0003_alter_field_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyAnalytics",
            fields=[
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="surveys.survey",
                    ),
                ),
                ("total_responses", models.PositiveIntegerField()),
                ("completed_responses", models.PositiveIntegerField()),
                ("unique_users", models.PositiveIntegerField()),
                ("max_responses", models.PositiveIntegerField()),
                ("average_responses_per_user", models.FloatField()),
                (
                    "max_responses_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="surveys.section",
                    ),
                ),
                (
                    "survey_analytics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_analytics",
                        to="surveys.surveyanalytics",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_responses", models.PositiveIntegerField()),
                ("common_responses", models.JSONField(default=list)),
                ("for_number", models.JSONField(default=dict, null=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="surveys.field"
                    ),
                ),
                (
                    "section_analytics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_analytics",
                        to="surveys.sectionanalytics",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("section_analytics", "field"),
                        name="unique_section_analytics_field",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sectionanalytics",
            constraint=models.UniqueConstraint(
                fields=("survey_analytics", "section"),
                name="unique_survey_analytics_section",
            ),
        ),
    ]
